#!/bin/bash
echo "print storage details of mahine"
echo "______________"
echo "df -h"
echo "print memory details of machine"
echo "free -g"
echo "______________"
echo "print generic details of machine"
echo "who && uname -r"
echo "______________"
